nf-core/scrnaseq

environment.yml
Same issue as https://github.com/nf-core/rnaseq/pull/214
Many thanks to contributing to nf-core/scrnaseq!
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md
=> Fix matplotlib version

.travis.yml, conf/base.config, conf/test_kallisto.config, docs/usage.md, main.nf, nextflow.config
Many thanks to contributing to nf-core/scrnaseq!
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).
**Learn more about contributing:** https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md
=> Small Updates 

.github/workflows/ci.yml, .travis.yml, CHANGELOG.md, Dockerfile, conf/test.config, docs/usage.md, environment.yml, main.nf, nextflow.config
This attempts to fix #20 and #21 in 1.0.1
=> PR for 1.0.1 Bugfixes

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
This is for the minor release before porting to DSL2
=> For minor release v1.1.0

docs/usage.md, nextflow_schema.json
=>  All the docs removed from usage.md and moved to json schema

modules/local/alevinqc.nf
The report filename was overwritten in case of multiple samples.
Also, due to an outdated container image, fonts were not
rendered properly in the plots within the report.
=> Fix alevinqc

conf/test_full.config
Started working on full-test profile, needs proper human reference + gtf now though
=> Add AWS Full Size Tests

README.md, assets/samplesheet.csv, docs/output.md, docs/usage.md, lib/WorkflowMain.groovy, nextflow.config, nextflow_schema.json
=> Updating docs

conf/test_full.config
=> fix full test

conf/test_full.config
=> Fixes full tests with 10x references

CHANGELOG.md, README.md, nextflow.config
This just fixes a couple of points, e.g. adding @grst to the contributors and the badges that were missing. Also bumps to 2.0.1dev now.
=> Bump version dev

modules/local/mtx_to_seurat.nf
Hi @apeltzer,
This is a very small fix to change the paths of kallisto files after module update.
=> fixing paths after kallisto update

conf/modules.config, modules.json, modules/nf-core/modules/custom/dumpsoftwareversions/main.nf, modules/nf-core/modules/kallistobustools/count/main.nf, modules/nf-core/modules/multiqc/main.nf
This PR is related to the issues we've been facing with `kallisto` after changing it to use `nf-core/modules`. It also tries to address the issue reported in #116.
=> PR: kallisto fix

modules/local/mtx_to_h5ad.nf
Hi!,
This is a very small PR to only fix a code-conditional that was missing an "else-if".
=> FIX: add "else if" instead of if-if

modules/local/simpleaf_index.nf
=> Repair inconsistency

CHANGELOG.md, nextflow.config
Just bumps to 2.1.1dev and adds changelog for that
=> Bump to 2.1.1dev

.github/workflows/ci.yml
Just updating the concurrency group to match the format used in nf-core tools which provides more context info.
=> updated concurrency groups to match nf-core tools

bin/check_samplesheet.py
=> Fixing small bug in check_samplesheet

modules/local/star_align.nf, nextflow.config, nextflow_schema.json, subworkflows/local/starsolo.nf, workflows/scrnaseq.nf
=> Add single-nucleus, RNA velocity option on star.

CHANGELOG.md, workflows/scrnaseq.nf
Hey Hey,
This is a quick fix related to #177 
Just needed to adjust the channel generations and usage when skipping fastqc.
=> fix skip_fastqc channel generations

CHANGELOG.md, conf/modules.config, nextflow.config, nextflow_schema.json
Fixes #173 by simply fixing the parameter type to boolean and adding it to `modules.config` to affect the modules that should be affected by it.
=> 173 should save reference parameter be boolean

CHANGELOG.md, modules/local/mtx_to_seurat.nf
=> Fix Seurat container

nextflow.config
=> bump version

CHANGELOG.md, nextflow.config
=> Readying for 2.3.0 release

.github/workflows/awsfulltest.yml, .github/workflows/awstest.yml, CHANGELOG.md, conf/public_aws_ecr.config, nextflow.config
Adds `public_aws_ecr` profile for using the ECR hosted contianers.
=> Public aws ecr profile

workflows/scrnaseq.nf
=> Fix code comment

CHANGELOG.md, conf/modules.config, conf/public_aws_ecr.config, modules.json, modules/local/mtx_to_seurat.nf, modules/nf-core/cellranger/count/main.nf, modules/nf-core/cellranger/mkgtf/main.nf, modules/nf-core/cellranger/mkref/main.nf, modules/nf-core/cellranger/mkref/meta.yml, modules/nf-core/kallistobustools/count/meta.yml, modules/nf-core/universc/README.md, modules/nf-core/universc/main.nf, nextflow.config
x-ref: https://github.com/nf-core/modules/pull/3497
=> Move containers for pipeline to quay.io

CHANGELOG.md, docs/usage.md, modules.json, modules/nf-core/cellranger/count/README.md, modules/nf-core/cellranger/count/main.nf, modules/nf-core/cellranger/count/meta.yml, modules/nf-core/cellranger/count/templates/cellranger_count.py, modules/nf-core/fastqc/main.nf
~~Merge #245 first!!~~
Updates the cellrangermodule to the latest version that automatically renames files. 
Fixes #241
Fixes #147 
Fixes #195
=> Update cellranger module

CHANGELOG.md, conf/base.config
=> increase time limits

workflows/scrnaseq.nf
Include missing aligner in checker.
=> Include cellrangerarc in checker

CHANGELOG.md, modules.json, modules/nf-core/cellranger/mkref/main.nf, modules/nf-core/cellrangerarc/mkref/main.nf
=> Update cellranger mkref modules

main.nf, workflows/scrnaseq.nf
This does not have any effect on the pipeline logic - it only rearranges code to make it more understandable and more similar to other nf-core pipelines
=> Improve genome attribute handling

modules/local/star_align.nf, modules/local/templates/mtx_to_h5ad_star.py, subworkflows/local/starsolo.nf, tests/main_pipeline_star.nf.test.snap
While it was already possible to compute the spliced and unspliced counts, they were not added to the final AnnData object. I added this functionality with this PR
=> Finalize STAR velocity implementation
